CREATE TABLE IF NOT EXISTS books (
    book VARCHAR PRIMARY KEY NOT NULL,
    type VARCHAR,
    authors VARCHAR,
    local_id VARCHAR,
    publish_date VARCHAR,
    publishers VARCHAR,
    source_records VARCHAR,
    title VARCHAR,
    works VARCHAR,
    key VARCHAR,
    covers VARCHAR,
    identifiers VARCHAR,
    isbn_10 VARCHAR,
    isbn_13 VARCHAR,
    classifications VARCHAR,
    languages VARCHAR,
    subtitle VARCHAR,
    latest_revision INTEGER,
    revision INTEGER,
    created VARCHAR,
    last_modified VARCHAR,
    number_of_pages FLOAT,
    notes VARCHAR,
    edition_name VARCHAR,
    physical_format VARCHAR,
    weight VARCHAR,
    physical_dimensions VARCHAR,
    publish_country VARCHAR,
    other_titles VARCHAR,
    subjects VARCHAR,
    subject_places VARCHAR,
    by_statement VARCHAR,
    publish_places VARCHAR,
    pagination VARCHAR,
    oclc_numbers VARCHAR,
    lc_classifications VARCHAR,
    dewey_decimal_class VARCHAR,
    contributors VARCHAR,
    series VARCHAR,
    translation_of VARCHAR,
    table_of_contents VARCHAR,
    full_title VARCHAR,
    ocaid VARCHAR,
    contributions VARCHAR,
    ia_box_id VARCHAR,
    ia_loaded_id VARCHAR,
    copyright_date VARCHAR,
    lccn VARCHAR,
    first_sentence VARCHAR,
    description VARCHAR,
    subject_time VARCHAR,
    genres VARCHAR,
    links VARCHAR
);


CREATE TABLE IF NOT EXISTS my_table (
    id VARCHAR PRIMARY KEY,
    kind VARCHAR,
    timestamp TIMESTAMP,
    comment VARCHAR,
    changes VARCHAR,
    author VARCHAR,
    ip VARCHAR,
    data VARCHAR,
    date TIMESTAMP,
    book VARCHAR,
    FOREIGN KEY (book) REFERENCES books(book)
);
